apiVersion: v1
kind: Service
metadata:
  name: readynest-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: readynest-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
