[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#00F5FF"
backgroundColor = "#020B2D"
secondaryBackgroundColor = "#061B4A"
textColor = "#F8FAFC"
font = "sans serif"
